name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request: {}

jobs:
  semgrep:
    name: Semgrep PR scan
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    uses: Talend/github-actions/.github/workflows/semgrep.yml@semgrep
